highlighter: rouge
markdown: kramdown
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://dmitryzuev.github.io
author: Dmitry Zuev

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: ''
title: "Dmitry Zuev: Ruby / Ruby on Rails Developer."
description: Open to remote, part-time and full-time job ruby developer from Russia.
name: Dmitry Zuev
email: mail@dmitryzuev.com
email_full: mailto:mail@dmitryzuev.com
website: dmitryzuev.github.io
website_full: https://dmitryzuev.github.io
github: dmitryzuev
twitter: dzuev
tel: +7 915 038-38-86
tel_full: tel:+79150383886
google_maps: 'https://www.google.com/maps/place/Donskaya+16,+Moscow,+Russia'
address: Donskaya ul., 16
postcode: 119049
city: Moscow
country: Russia
google_analytics: ''

# needed for travis-ci build
exclude: [vendor]
